name: Content Deployment

on:
  repository_dispatch:
    types: [content-update]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website code
        uses: actions/checkout@v3
      
      - name: Checkout content repository
        uses: actions/checkout@v3
        with:
          repository: fending/bfdc-content
          token: ${{ secrets.CONTENT_REPO_TOKEN }}
          path: bfdc-content
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Copy new image assets
        run: |
          # Create target directory if it doesn't exist
          mkdir -p public/images
          
          # Copy images from bfdc-content that don't already exist in public/images
          for image in bfdc-content/content/assets/images/*; do
            if [ -f "$image" ]; then
              filename=$(basename "$image")
              if [ ! -f "public/images/$filename" ]; then
                echo "Copying new image: $filename"
                cp "$image" "public/images/"
              else
                echo "Skipping existing image: $filename"
              fi
            fi
          done
      
      - name: Build website
        run: npm run build
        env:
          GITHUB_CONTENT_URL: 'https://raw.githubusercontent.com/fending/bfdc-content/main'
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'