name: Content Sync and Trigger Vercel Deploy

on:
  repository_dispatch:
    types: [content-update]
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website code
        uses: actions/checkout@v3
      
      - name: Checkout content repository
        uses: actions/checkout@v3
        with:
          repository: fending/bfdc-content
          token: ${{ secrets.CONTENT_REPO_TOKEN }}
          path: bfdc-content
          ref: main
      
      - name: Copy new image assets
        run: |
          # Create target directory if it doesn't exist
          mkdir -p public/images
          
          # Copy images from bfdc-content that don't already exist in public/images
          for image in bfdc-content/content/assets/images/*; do
            if [ -f "$image" ]; then
              filename=$(basename "$image")
              if [ ! -f "public/images/$filename" ]; then
                echo "Copying new image: $filename"
                cp "$image" "public/images/"
              else
                echo "Skipping existing image: $filename"
              fi
            fi
          done
      
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}